name: weighty
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  google_fonts: ^6.0.0
  syncfusion_flutter_charts: ^23.1.36
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  firebase_storage: ^11.2.7
  font_awesome_flutter: ^10.5.0
  image_picker: ^1.0.4
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  get: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  image_path: "assets/images/1024.png"

flutter: 
  uses-material-design: true
  assets:
    - assets/svgs/icons/
    - assets/svgs/illustrations/
    - assets/images/png/
